### ISSUE TITLE
ERROR in HtmlWebpackPlugin: Unable to read HTML template "html-withimg-loader!F:\webpack\src\view\template.html"

### ISSUE THREAD

**Issue by GuYunWei** [wzsxyz/html-withimg-loader#1]
new HtmlWebpackPlugin({                             
           favicon:'./src/images/favicon.ico',                 
            template:'./src/view/template.html',                
            template: 'html-withimg-loader!'+path.resolve(srcDir, 'view/template.html'),
            filename:'/view/index.html',                     
            inject:true,                                      
            hash:true,                                       
            minify:{                                        
                removeComments:true,                         
                collapseWhitespace:false                       
            }
        })
试了很多办法，就是报错，请问这可能是什么原因

**Comment by wzsxyz** [comment]
兄弟你一个对象中配置两个template字段是什么意思？按js语法逻辑，第二个是要被忽略的，所以你根本没使用html-withimg-loader。错误是你第一个template造成的

**Comment by leeleoo** [comment]
ERROR in HtmlWebpackPlugin: Unable to read HTML template "html-withimg-loader!/Users/leo/AFT/tencent-popular/html-template/index.html"

mac下也出现这样的问题

`
    new HtmlwebpackPlugin({
      title: '123123123123',
      template: 'html-withimg-loader!' + path.resolve(TEM_PATH, 'index.html'),
      filename: 'index.html',
      chunks: ['app', 'vendors'],
      inject: 'body'
    })
`

**Comment by wzsxyz** [comment]
老版本的html-webpack-plugin不支持loader，你更新下html-webpack-plugin这个模块的版本试试

**Comment by lylpixin2121** [comment]
你好 我想咨询下，我的loader里做了这些处理

`loaders :[
			{test : /\.css$/ , loader : ExtractTextPlugin.extract("style",["css"])},
			{test : /\.scss$/ , loader : ExtractTextPlugin.extract("style",["css","sass"])},
			{test: /\.(htm|html)$/,loader: 'html-withimg-loader'},
			{test : /\.(jpg|png)$/ , loader : "url-loader?limit=8192"},
			{test: /\.(png|jpeg|gif)$/,loader: 'file-loader?name=./images/[name]-[sha512:hash:base64:7].[ext]'}
		]`，同时我的页面中引用了一张400多K大的图片 但是最后却把我页面中的图给编译成了base64 不知道是什么原因引起的，导致这张图最终还是没加载出来，我把项目地址是https://github.com/lylpixin2121/webpack-demo，如果您有时间 还麻烦帮忙看看 多谢了

**Comment by lylpixin2121** [comment]
这边测试出来了 因为是新增了一个file-loader的编译器做图片打包结果 导致出现了问题 不知道这算不算个bug

**Comment by wzsxyz** [comment]
不要同时使用file-loader与url-loader，都用url-loader处理，
{
test: /\.(jpe?g|png|gif|svg)$/i,
loader: 'url-loader?limit=1&minetype=image/jpg&name=images/[name]_[hash].[ext]'
}
limit注意设置，比limit小的图片会被base64编码

**Comment by lylpixin2121** [comment]
@wzsxyz  多谢  这么处理 确实解决了

**Comment by jqjiang** [comment]
template: 'html-withimg-loader!' + filePath,
filename: filename + '.html'
我在html-webpack-plugin这么配置以后，没有任何效果，编译也不报错
